package:
  version: "{{ load_setup_py_data().version }}"
  name: 'gbasis'

source:
  path: ../../

build:
  number: 0
  script: ./tools/libs/install_libint-2.0.3.sh; python setup.py install

requirements:
  build:
    - python
    - numpy
    - scipy
    - cython >=0.24.1
    - setuptools
    - nose
  run:
    - python
    - numpy
    - scipy
    - nose

about:
  home: https://github.com/theochem/gbasis
  license: GNU Version 3
